# Loading packages

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# Reading data

In [2]:
data = np.load('data.npy')
data.shape

(500, 501)

In [3]:
df = pd.DataFrame(data).add_prefix('col_')
df.head()

col_0      col_1      col_2  ...    col_498    col_499  col_500
0   48.849809   4.176348  -3.773606  ...   3.113201   3.808528      1.0
1 -100.695161  -1.841732  -5.260964  ... -13.083572  -0.874872      0.0
2   47.470485   8.163793   9.260559  ...  -3.908942  -1.271411      0.0
3   28.278859   1.874441  -9.080854  ... -16.206060   5.107095      0.0
4   37.098115 -19.084087 -11.064898  ...  11.430567 -10.994911      1.0

[5 rows x 501 columns]

In [4]:
X = df.iloc[:,:500]
y = df.iloc[:,-1]

In [5]:
print('X shape:', X.shape)
print('y shape:', y.shape)

X shape: (500, 500)
y shape: (500,)


# Construct PCA with parameter

In [6]:
pca = PCA(0.95)
X_reduced = pca.fit_transform(X)
X_reduced.shape

(500, 111)

In [7]:
pca.get_params

<bound method BaseEstimator.get_params of PCA(copy=True, iterated_power='auto', n_components=0.95, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)>

In [8]:
pca.n_components_

111

In [9]:
pca.singular_values_.shape

(111,)

In [10]:
pca.components_.T.shape

(500, 111)

In [11]:
pca.singular_values_

array([7262.98783628, 4381.08702523, 4358.04818196, 4170.33305628,
       4118.1799965 , 4033.98564431, 3920.06304998, 3870.09970736,
       3812.35237241, 3733.84041826, 3641.37309789, 3587.93609273,
       3569.52470931, 3483.26417526, 3381.87543289, 3351.16443429,
       3308.26722888, 3250.47081944, 3223.25443336, 3176.96160986,
       3156.80618414, 3110.99766752, 3087.2362416 , 3032.33900884,
       2980.62453384, 2954.39986527, 2912.32253117, 2889.97462916,
       2859.14934184, 2809.49519004, 2769.94781944, 2744.92874963,
       2723.6868696 , 2685.10370447, 2634.25592426, 2618.10187307,
       2576.06278605, 2518.18673073, 2496.03300039, 2477.18316716,
       2453.70651904, 2420.73334507, 2405.06861878, 2384.17416266,
       2356.09173714, 2286.90842133, 2274.05168484, 2237.42783981,
       2215.38183568, 2201.66779181, 2158.29699425, 2149.12364208,
       2130.85654259, 2109.39136999, 2083.480016  , 2069.29253112,
       2039.78741378, 2018.16635686, 1973.8612028 , 1958.44221

In [12]:
pca.explained_variance_ratio_.sum()

0.9501890519849235

In [13]:
pca.explained_variance_ratio_.cumsum()

array([0.07317687, 0.09980294, 0.1261497 , 0.15027567, 0.17380198,
       0.19637616, 0.21769331, 0.23847054, 0.25863234, 0.27797226,
       0.29636615, 0.31422414, 0.33189933, 0.34873057, 0.36459624,
       0.38017506, 0.3953576 , 0.41001428, 0.42442655, 0.43842782,
       0.45225199, 0.46567786, 0.47889943, 0.49165496, 0.50397914,
       0.5160874 , 0.52785322, 0.53943916, 0.55077926, 0.5617289 ,
       0.57237244, 0.58282459, 0.59311559, 0.60311709, 0.61274339,
       0.62225198, 0.63145766, 0.64025435, 0.64889694, 0.65740948,
       0.66576145, 0.67389045, 0.68191458, 0.6897999 , 0.69750055,
       0.70475561, 0.71192932, 0.71887382, 0.72568215, 0.73240645,
       0.73886843, 0.74527559, 0.7515743 , 0.75774675, 0.76376849,
       0.7697085 , 0.77548032, 0.78113043, 0.78653519, 0.79185585,
       0.79705356, 0.80221005, 0.8070985 , 0.8119599 , 0.81669752,
       0.82139952, 0.82597076, 0.83048402, 0.83486772, 0.83913755,
       0.84336157, 0.84745029, 0.85142954, 0.85534954, 0.85922

In [14]:
pca.explained_variance_ratio_

array([0.07317687, 0.02662606, 0.02634676, 0.02412597, 0.02352631,
       0.02257418, 0.02131716, 0.02077722, 0.0201618 , 0.01933992,
       0.01839389, 0.01785799, 0.01767519, 0.01683124, 0.01586567,
       0.01557882, 0.01518254, 0.01465669, 0.01441227, 0.01400126,
       0.01382417, 0.01342587, 0.01322157, 0.01275554, 0.01232417,
       0.01210826, 0.01176582, 0.01158594, 0.0113401 , 0.01094964,
       0.01064355, 0.01045214, 0.010291  , 0.0100015 , 0.00962629,
       0.00950859, 0.00920568, 0.00879669, 0.00864259, 0.00851255,
       0.00835196, 0.008129  , 0.00802413, 0.00788532, 0.00770065,
       0.00725506, 0.00717371, 0.0069445 , 0.00680833, 0.0067243 ,
       0.00646198, 0.00640717, 0.00629871, 0.00617245, 0.00602174,
       0.00594001, 0.00577182, 0.00565011, 0.00540476, 0.00532065,
       0.00519771, 0.0051565 , 0.00488844, 0.0048614 , 0.00473762,
       0.00470201, 0.00457123, 0.00451326, 0.00438371, 0.00426982,
       0.00422403, 0.00408872, 0.00397925, 0.00392   , 0.00387

---

# Construct PCA without parameter

In [15]:
pca2 = PCA()
pca2.fit(X)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [16]:
cumsum = np.cumsum(pca2.explained_variance_ratio_)
d = np.argmax(cumsum >= 0.95) + 1
d

111

In [17]:
pca2.explained_variance_ratio_.sum()

1.0

In [18]:
x_ax = np.linspace(1, 500, 500)
y_ax = pca2.explained_variance_ratio_.cumsum()

In [19]:
fig = px.line(x=x_ax, y=y_ax, title='Variance vs Dimensions', labels={'x':'Dimensions', 'y':'Explained Variance'})
fig.show()

In [20]:
per_var = np.round(pca2.explained_variance_ratio_ * 100, decimals=1)
labels = ['PC' + str(x) for x in range(1, len(per_var)+1)]

fig = px.bar(x=labels[:200], y=per_var[:200], labels={'x':'Principal Components', 'y':'Percentage of Explained Variance'})
fig.show()

---

# Making pipeline

In [21]:
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import f1_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [23]:
model = Pipeline([
                  ('pca', PCA(0.95)),
                  ('clf', KNeighborsClassifier(n_neighbors=1))
                ])

In [24]:
model.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('pca',
                 PCA(copy=True, iterated_power='auto', n_components=0.95,
                     random_state=None, svd_solver='auto', tol=0.0,
                     whiten=False)),
                ('clf',
                 KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                      metric='minkowski', metric_params=None,
                                      n_jobs=None, n_neighbors=1, p=2,
                                      weights='uniform'))],
         verbose=False)

In [25]:
model.score(X_train, y_train)

1.0

In [26]:
model.score(X_test, y_test)

0.9866666666666667

In [27]:
f1_score(y_train, model.predict(X_train))

1.0

In [28]:
f1_score(y_test, model.predict(X_test))

0.9855072463768116